import Link from 'next/link'
import { getPosts } from '../lib/mdxUtils'

export function Index({ posts }) {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link as={`/posts/${post.slug}`} href={`/posts/[slug]`}>
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  )
}

export function getStaticProps() {
  return { props: { posts: getPosts() } }
}

export default Index
